services:
  mailforwarder:
    image: jmdirksen/mailforwarder
    ports:
      - "25:25"
    environment:
      HOSTNAME: "mail.example.com"
      DOMAINS: "example.com other.com"
      FORWARD1: "@example.com myaddress@gmail.com"
      FORWARD2: "test@other.com myaddress@gmail.com"
    restart: unless-stopped
